# Generated by Django 5.2 on 2025-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("player", models.CharField(max_length=255)),
                ("now_money", models.SmallIntegerField()),
                ("total", models.SmallIntegerField()),
            ],
            options={
                "db_table": "news_data",
            },
        ),
        migrations.CreateModel(
            name="TopPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("player", models.CharField(max_length=255)),
                ("now_money", models.SmallIntegerField()),
                ("total", models.SmallIntegerField()),
            ],
        ),
    ]
