# Generated by Django 5.2 on 2025-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mahjong_db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MahjongRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("player", models.CharField(max_length=50)),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="NewsData",
        ),
        migrations.DeleteModel(
            name="TopPerson",
        ),
    ]
